# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-15 17:05
from __future__ import unicode_literals

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=60)),
                ('address_line_2', models.CharField(blank=True, max_length=60, null=True)),
                ('town_city', models.CharField(max_length=60)),
                ('county', models.CharField(blank=True, max_length=60, null=True)),
                ('postcode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=10)),
                ('birth_date', models.DateField()),
                ('weight', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_location)),
                ('allowed_club_change', models.BooleanField(default=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competitions.Activity')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Address')),
                ('football_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.FootballClub')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
