# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-16 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_totoal_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='totoal_points',
            new_name='total_points',
        ),
    ]
