# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-13 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_auto_20161012_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='details',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
