# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-15 17:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_workoutstats_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutstats',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
