# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-15 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_auto_20161015_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutstats',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.Activity'),
        ),
    ]
