# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-15 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_auto_20161015_1946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkoutStats',
            new_name='Workout',
        ),
    ]
