# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-17 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_auto_20161015_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='total_calories_burnt',
            new_name='total_calories_burned',
        ),
    ]
