# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-23 19:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0014_topcompetitors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topcompetitors',
            name='first',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_top_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topcompetitors',
            name='second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_top_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topcompetitors',
            name='third',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_top_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
