# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-13 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0005_activity_football_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('football_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.FootballClub')),
            ],
        ),
    ]
