# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-13 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_activity_football_club'),
        ('clubadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='cycling_activities',
            field=models.ManyToManyField(related_name='cycling', to='competitions.Activity'),
        ),
        migrations.AddField(
            model_name='competition',
            name='running_activities',
            field=models.ManyToManyField(related_name='running', to='competitions.Activity'),
        ),
        migrations.AddField(
            model_name='competition',
            name='walking_activities',
            field=models.ManyToManyField(related_name='walking', to='competitions.Activity'),
        ),
    ]
