# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-15 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='football_club',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='competitions_football_club', to='competitions.FootballClub'),
        ),
    ]
