# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-13 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubadmin', '0002_auto_20161013_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='cycling_activities',
            field=models.ManyToManyField(blank=True, related_name='cycling', to='competitions.Activity'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='running_activities',
            field=models.ManyToManyField(blank=True, related_name='running', to='competitions.Activity'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='walking_activities',
            field=models.ManyToManyField(blank=True, related_name='walking', to='competitions.Activity'),
        ),
    ]
