# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-14 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_activity_football_club'),
        ('clubadmin', '0003_auto_20161013_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='cycling_activities',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='running_activities',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='walking_activities',
        ),
        migrations.AddField(
            model_name='competition',
            name='current_cycling_activity',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='current_cycling_activity', to='competitions.Activity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='current_running_activiy',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='current_running_activiy', to='competitions.Activity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='current_walking_activity',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='current_walking_activity', to='competitions.Activity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='next_cycling_activity',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='next_cycling_activity', to='competitions.Activity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='next_running_activiy',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='next_running_activiy', to='competitions.Activity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='next_walking_activity',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='next_walking_activity', to='competitions.Activity'),
            preserve_default=False,
        ),
    ]
