# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-14 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubadmin', '0004_auto_20161014_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='current_walking_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_walking_activity', to='competitions.Activity'),
        ),
    ]
