# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-14 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubadmin', '0005_auto_20161014_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='current_cycling_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_cycling_activity', to='competitions.Activity'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='current_running_activiy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_running_activiy', to='competitions.Activity'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='next_cycling_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_cycling_activity', to='competitions.Activity'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='next_running_activiy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_running_activiy', to='competitions.Activity'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='next_walking_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_walking_activity', to='competitions.Activity'),
        ),
    ]
