# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-14 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_activity_football_club'),
        ('clubadmin', '0006_auto_20161014_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='current_running_activiy',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='next_running_activiy',
        ),
        migrations.AddField(
            model_name='competition',
            name='current_running_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_running_activity', to='competitions.Activity'),
        ),
        migrations.AddField(
            model_name='competition',
            name='next_running_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_running_activity', to='competitions.Activity'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='current_walking_activity',
            field=models.ForeignKey(blank=True, help_text='Enter the current walking activiy for competition', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_walking_activity', to='competitions.Activity'),
        ),
    ]
